
    spring:
        datasource:
            url:    jdbc:mysql://0.0.0.0:3306/suds?autoReconnect=true&useSSL=false
            username:   root
            password:   password
        jpa:
            hibernate:
                ddl-auto:   create
