
    spring:
        datasource:
            url:    jdbc:mysql://ec2-3-17-147-233.us-east-2.compute.amazonaws.com:3306/suds?autoReconnect=true&useSSL=false
            username:   root
            password:   password
        jpa:
            hibernate:
                ddl-auto:   create
