
    spring:
        datasource:
            url:    jdbc:mysql://localhost:3306/demo
            username:   root
            password:   root
        jpa:
            hibernate:
                ddl-auto:   create